group 'com.hugocornellier.flutter_litert'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.6.1'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 36
    namespace 'com.hugocornellier.flutter_litert'

    externalNativeBuild {
        cmake {
            path "../src/CMakeLists.txt"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        minSdkVersion 21

    }
}


dependencies {
    def litert_version = "1.4.1"

    implementation("com.google.ai.edge.litert:litert:${litert_version}")
    implementation("com.google.ai.edge.litert:litert-gpu:${litert_version}")
}
