#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output="$repo_root/ios/flutter_litert/Sources/flutter_litert_delegate_symbols/flutter_litert_delegate_symbols.c"
symbols_file="$(mktemp)"
trap 'rm -f "$symbols_file"' EXIT

frameworks=(
  TensorFlowLiteC
  TensorFlowLiteCMetal
  TensorFlowLiteCCoreML
)

for framework in "${frameworks[@]}"; do
  binary="$repo_root/ios/$framework.xcframework/ios-arm64/$framework.framework/$framework"
  if [[ ! -f "$binary" ]]; then
    printf 'Missing iOS framework binary: %s\n' "$binary" >&2
    exit 1
  fi
  nm -gU "$binary" | awk '$2 == "T" { sub(/^_/, "", $3); print $3 }'
done | LC_ALL=C sort -u > "$symbols_file"

if [[ ! -s "$symbols_file" ]]; then
  printf 'No exported iOS FFI symbols found.\n' >&2
  exit 1
fi

if rg -n -v '^[A-Za-z_][A-Za-z0-9_]*$' "$symbols_file"; then
  printf 'Generated symbol list contains invalid C identifiers.\n' >&2
  exit 1
fi

{
  cat <<'HEADER'
// Generated by scripts/generate_ios_ffi_symbol_anchor.sh. Do not edit.
//
// Dart FFI resolves LiteRT functions through dlsym(RTLD_DEFAULT), so the
// native linker cannot discover these references from Dart code. Keep every
// exported C entry point from the packaged iOS frameworks reachable here to
// prevent Flutter, CocoaPods, and App Store/TestFlight stripping from removing
// symbols that Dart may resolve at runtime.

#include "include/flutter_litert_delegate_symbols.h"

#if defined(__arm64__) || defined(FLUTTER_LITERT_COCOAPODS)
// Emit static framework link options from this retained object so CocoaPods
// links the APIs into Runner and SwiftPM links them into its embedded dynamic
// plugin framework. The dynamic SwiftPM product preserves the public export
// table when Xcode archives and strips the consuming app.
//
// The published SPM simulator artifacts currently contain arm64 slices only.
// CocoaPods defines FLUTTER_LITERT_COCOAPODS and ships universal simulator
// slices, so its Intel simulator build retains the same symbols.
__asm__(".linker_option \"-framework\", \"TensorFlowLiteC\"\n");
__asm__(".linker_option \"-framework\", \"TensorFlowLiteCMetal\"\n");
__asm__(".linker_option \"-framework\", \"TensorFlowLiteCCoreML\"\n");

HEADER

  while IFS= read -r symbol; do
    printf 'extern void %s(void);\n' "$symbol"
  done < "$symbols_file"

  cat <<'MIDDLE'

static const void* volatile g_ffi_symbol_anchor;
#endif

void FlutterLitertRetainFfiSymbols(void) {
#if defined(__arm64__) || defined(FLUTTER_LITERT_COCOAPODS)
MIDDLE

  while IFS= read -r symbol; do
    printf '  g_ffi_symbol_anchor = (const void*)&%s;\n' "$symbol"
  done < "$symbols_file"

  cat <<'FOOTER'
#endif
}
FOOTER
} > "$output"

printf 'Generated %s retained iOS FFI symbols in %s\n' "$(wc -l < "$symbols_file" | tr -d ' ')" "$output"
